### ISSUE TITLE
"Limited user" on twitter make the fetching request loop forever

### ISSUE THREAD

**Issue by FlorentLefebvre** [eleurent/twitter-graph#15]
When an user is limited on twitter (due for example to bad behaviour), the fetching request will try it forever.

To bypass that, you need to stop the process, erase this follower from the "follower.json" cache, update your code to bypass "fetch_users" and use your cache instead (to not update your cache with the complete list of users of you target, containing the "limited user").

I will try to update this issue with an example next time a found a "limited user".

**Comment by eleurent** [comment]
Is there a specific exception for limited users, that we can try to catch?
As a slightly better workaround: when a limited user is found, the username can be simply added to an excluded.json file, and it will be skipped (no need to erase follower.json nor to change the code).
