### ISSUE TITLE
Http server not work

### ISSUE THREAD

**Issue by Leod88** [eleurent/twitter-graph#26]
I have everything set up as explained. But it doesn't seem to work completely. 
I have the CSV of the nodes and the CSV of the edges but the http page doesn't open. 
I have no idea what the problem is. 

I use this command: Python  fetch_data.py users  "my target user" --run-http-server

![image](https://user-images.githubusercontent.com/87878066/152874564-fe08fa8b-4340-44dd-8b30-bf96cb63df56.png)

**Comment by eleurent** [comment]
Fixed in a8dd51a4d29b6a069668a4fa83014d776a4585f8

**Comment by Leod88** [comment]
Nice ! Thanks a lot
