### ISSUE TITLE
save_to_graph() got an unexpected keyword argument 'filtering'

### ISSUE THREAD

**Issue by Cruzaderx** [eleurent/twitter-graph#32]
I failed to figure out what causing this problem.
Traceback (most recent call last):
  File "/home/username/Downloads/twitter-graph/fetch_data.py", line 322, in <module>
    main()
  File "/home/username/Downloads/twitter-graph/fetch_data.py", line 314, in main
    save_to_graph(users, friendships, Path(options["--out"]), target, filtering=options["--filtering"],
TypeError: save_to_graph() got an unexpected keyword argument 'filtering'

**Comment by eleurent** [comment]
Hey, this bug was introduced yesterday and then fixed a few hours ago, maybe you got the broken version?
Could you please try updating to the current main and see if this fixes the issue?

**Comment by Cruzaderx** [comment]
Yea ill update i DL your awesome app last night so you're i got a broken version.
