### ISSUE TITLE
Twitter API - elevated access required

### ISSUE THREAD

**Issue by dcbuild3r** [eleurent/twitter-graph#35]
After having instantiated the repo with my own credentials and hitting the Twitter API the responses was:

```
[{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. 
If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal.
 You can learn more here: 
 https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]
```

I have submitted the request for elevated API access for Twitter, but this is not mentioned in the README, maybe it is worth considering adding this procedure.

**Comment by eleurent** [comment]
Hi!
Interesting, I don't remember having to go through this step... Maybe this is a recent addition on Twitter's side?
I will briefly mention it in the README in case anybody else runs into this.
Thanks for the feedback!
