### ISSUE TITLE
Citation file

### ISSUE THREAD

**Issue by paulodiogo** [eleurent/twitter-graph#39]
Hello, it's a amazing job here, thank you!

I'm writing my thesis and I want to citate this repository, is it possible to you guys add a Citation File?

https://citation-file-format.github.io/

Thank you!

**Comment by eleurent** [comment]
Hi Paul, sorry for the late replay, and thanks a lot for suggesting this and for the credit! 
I am very much looking forward to reading your thesis ;)

**Comment by paulodiogo** [comment]
> Hi Paulo, sorry for the late replay, and thanks a lot for suggesting this and for the credit! I am very much looking forward to reading your thesis ;)

Thank you!
