### ISSUE TITLE
previous and next cursors variables are reversed resulting in a 5000 friends dump limit

### ISSUE THREAD

**Issue by stygmate** [eleurent/twitter-graph#43]
https://github.com/eleurent/twitter-graph/blob/dc5b742f6ac72609ec88647f6cf45e0455b15b2d/app/fetch_data.py#L172

**Comment by eleurent** [comment]
Mmmh, looks like this happened with the switch from python-twitter to tweepy  ([PR](https://github.com/eleurent/twitter-graph/pull/40)).
Are you positive the right order should be `(previous, next)`? I can't find anything in the documentation, it looks like we're supposed to use the [Cursor](https://docs.tweepy.org/en/stable/v1_pagination.html) class... and [get_friends_id](https://docs.tweepy.org/en/stable/api.html#tweepy.API.get_friend_ids) is supposed to just return a List[int]

**Comment by stygmate** [comment]
if i remember `get_friends_id` return `(previous_cursor, next_cursor), list` if `cursor` parameter is filled.
I have tested and it seems to work well.

**Comment by eleurent** [comment]
Yes I think you're right. This is now fixed, thanks a lot!
